export const algorithmDisplayNames = {
	avlTree: 'AVL Tree',
	bellmanFordShortestPath: 'Bellman–Ford Shortest Path',
	binaryTree: 'Binary Tree',
	jarvisMarch: 'Jarvis March',
	coinChange: 'Coin Change Algorithm',
	convexHull: 'Convex Hull (Brute Force)',
	dijkstraShortestPath: 'Dijkstra’s Shortest Path',
	factorialCalculator: 'Factorial Calculation',
	fractionalKnapsack: 'Fractional Knapsack (Without Repetition)',
	fractionalKnapsackRep: 'Fractional Knapsack (With Repetition)',
	grahamScan: 'Graham Scan',
	heapSort: 'Heap Sort',
	hilbertCurves: 'Hilbert Curves',
	insertionSort: 'Insertion Sort',
	knuthMorrisPratt: 'Knuth–Morris–Pratt Algorithm',
	kruskalMinimumSpanningTree: 'Kruskal’s Algorithm',
	maxSumPath: 'Maximum Sum Path',
	mergeSort: 'Merge Sort',
	primMinimumSpanningTree: 'Prim’s Algorithm',
	quickSort: 'Quick Sort',
	rabinKarp: 'Rabin–Karp Algorithm',
	redBlackTree: 'Red–Black Tree',
	towersOfHanoi: 'Towers of Hanoi',
	travelingProblem: 'Traveling Salesman Problem (Greedy)',
};
